### ISSUE TITLE
How do I get converted files into Thunderbird?

### ISSUE THREAD

**Issue by harry643** [juanirm/pst-converter#1]
The conversion was successful however I can't import the output files into Thunderbird. How do I do this? The files are HTML not MBOX like the README says.

Also, what are the `.sbd` directories? There is no mention of these in the README.

Example of the file types I get as output:
```
$ file out/5db2f19c41144330b8c75bc1cb37d3cc.sbd/Inbox
Inbox: HTML document, Non-ISO extended-ASCII text, with very long lines (961)
```

**Comment by juanirm** [comment]
Hi, I am sorry to say this but it's been a long while since I worked on this and basically I leverage on other peoples tools. I just bundled them into the container image.
Regarding the .sbd directories, I believe they are just representing the folders within the mailbox.
The [Readpst man page](http://colby.id.au/importing-pst-files-into-thunderbird-using-libpst/) should be able to help you with the import. I don't recall any HTML file being outputted.

Let me know if you are not able to find a solution in the man page and I'll try to find if something changed from when I developed this.

**Comment by harry643** [comment]
Thank you for the response @juanirm. I found that Thunderbird 91.11.0 for Ubuntu doesn't recognise the mail folders when adding the single, top-level `.sbd` directory to the Thunderbird profile directory, the contents of it must be added instead.

**Comment by juanirm** [comment]
Ok, that's good to know. Hope you were able to get your emails.
